#
# Voice Signal Preprocess
# Copyright (C) 2001-2023 NationalChip Co., Ltd
# ALL RIGHTS RESERVED!
#
# Makefile: source list in dsp/vpa/arach_lib/src/ctc/decoder
#
#=================================================================================#

ifeq ($(CONFIG_LVP_RNN_SED_MODEL_V0_1_1_2024_0116), y)

MODEL_DIR_PRE  = lvp/vui/sed/models/rnn_sed/development/v0.1.1

INCLUDE_DIR    += $(MODEL_DIR_PRE)/
INCLUDE_DIR    += $(MODEL_DIR_PRE)/../
sed_objs   += $(MODEL_DIR_PRE)/sed_model.o

endif
