#
# Voice Signal Preprocess
# Copyright (C) 2001-2020 NationalChip Co., Ltd
#
# Makefile: base/ source list
#
#=================================================================================#

base_objs  = base/src/crc32.o
base_objs  += base/src/div64.o
