#
# Voice Signal Preprocess
# Copyright (C) 2001-2018 NationalChip Co., Ltd
# ALL RIGHTS RESERVED!
#
# Makefile: board/ source list
#
#=================================================================================#

-include boards/*/*/Makefile
