#
# Voice Signal Preprocess
# Copyright (C) 2001-2021 NationalChip Co., Ltd
# ALL RIGHTS RESERVED!
#
# Makefile: source list in lvp/vui/sed
#
#=================================================================================#

SED_DIR_PRE  = lvp/vui/sed
-include $(SED_DIR_PRE)/models/*/*/*/Makefile
-include $(SED_DIR_PRE)/models/*/*/Makefile
-include $(SED_DIR_PRE)/post_processing/*/*/Makefile
sed_objs    += $(SED_DIR_PRE)/sed_decode.o
