#
# Voice Signal Preprocess
# Copyright (C) 2001-2020 NationalChip Co., Ltd
# ALL RIGHTS RESERVED!
#
# Makefile: File List for Board
#
#=================================================================================#

ifeq ($(CONFIG_BOARD_GX8002B_AIOT_V1), y)
    boot_objs += boards/$(CONFIG_BOARD_VENDOR)/$(CONFIG_BOARD_MODEL)/boot_board.o
    boot_objs += boards/$(CONFIG_BOARD_VENDOR)/$(CONFIG_BOARD_MODEL)/audio_board.o
    boot_objs += boards/$(CONFIG_BOARD_VENDOR)/$(CONFIG_BOARD_MODEL)/clock_board.o
    dev_objs += boards/$(CONFIG_BOARD_VENDOR)/$(CONFIG_BOARD_MODEL)/misc_board.o
endif

