#
# Voice Signal Preprocess
# Copyright (C) 1991-2018 NationalChip Co., Ltd
# ALL RIGHTS RESERVED!
#
# Makefile: arch Makefile
#
#=================================================================================#

-include arch/soc/$(strip $(subst ", ,$(CONFIG_SOC_MODEL)))/Makefile
