#
# Voice Signal Preprocess
# Copyright (C) 2001-2020 NationalChip Co., Ltd
# ALL RIGHTS RESERVED!
#
# Makefile: lvp/common source list
#
#=================================================================================#

#ifeq ($(CONFIG_LVP_APP_NONE), n)
app_objs += lvp/app_core/lvp_app_core.o
#endif

