#
# Voice Signal Preprocess
# Copyright (C) 2001-2018 NationalChip Co., Ltd
#
# Makefile: base/ source list
#
#=================================================================================#

base_objs += base/libc/tinyprintf.o
base_objs += base/libc/vsprintf.o
base_objs += base/libc/vprintf.o
#CCFLAGS  += -DPRINTF_DISABLE_SUPPORT_EXPONENTIAL
#base_objs += base/libc/printf.o
base_objs += base/libc/memcpy.o
base_objs += base/libc/memset.o
base_objs += base/libc/vsscanf.o
base_objs += base/libc/libc_port.o
base_objs += base/libc/atoi.o
base_objs += base/libc/strcpy.o
base_objs += base/libc/strcmp.o
base_objs += base/libc/strlen.o
