#
# Voice Signal Preprocess
# Copyright (C) 2001-2020 NationalChip Co., Ltd
# ALL RIGHTS RESERVED!
#
# Makefile: source list in dsp/vpa/arach_lib/src/ctc/decoder
#
#=================================================================================#

ifeq ($(CONFIG_POST_PROCESSING_DEVELOPMENT_V0_0_1_2023_0725), y)

POST_PROCESSING_DIR_PRE  = lvp/vui/sed/post_processing/

INCLUDE_DIR    += $(POST_PROCESSING_DIR_PRE)/
sed_objs   += $(POST_PROCESSING_DIR_PRE)/development/v0.0.1/sed_post_processing.o

endif
