#!/bin/bash
#####################################################################################################
# liuyx@nationalchip.com
# Copyright (C), 2013-2020, HangZhou NationalChip Sceince and Technology Corp.
# Parse .config file, generate config header/source file, copy resource needed
#####################################################################################################
if [ -e .config ];then
	source .config
else
	echo "Cannot find .config file, please config first"
	echo "make menuocnfig"
	exit 1
fi

#####################################################################################################
# Set some important variable by manual
CONFIG_BUILD_DIR=$(pwd)
CONFIG_FILE_H=${CONFIG_BUILD_DIR}/include/autogenerated_config.h
#
###################################### copy resource ################################################
# do something

#####################################################################################################

#build config file .h and .c 
##.h
echo "#ifndef __AUTOGENERATED_CONFIG_H__" >$CONFIG_FILE_H
echo "#define __AUTOGENERATED_CONFIG_H__">>$CONFIG_FILE_H
echo "/*">>$CONFIG_FILE_H
echo " * DO NOT MODIFY.">>$CONFIG_FILE_H
echo " *">>$CONFIG_FILE_H
echo " * This file was generated by Makefile">>$CONFIG_FILE_H
echo " *">>$CONFIG_FILE_H
echo " */">>$CONFIG_FILE_H
echo "">>$CONFIG_FILE_H


echo "">>$CONFIG_FILE_H
echo "#endif">>$CONFIG_FILE_H

