#ifndef __VUI_CONF_H__
#define __VUI_CONF_H__
// VUI Settings
//

//
// VAD Settings:
//
#define CONFIG_LVP_FFT_VAD_ENABLE
#define CONFIG_LVP_FFT_INVALID_VAD_NUM 25
#define CONFIG_LVP_VAD_FALLBACK_CONTEXT 4
// CONFIG_LVP_ENABLE_AUTO_ADJUST_VAD_PARAMETER is not set

//
// 
//

//
// ENV Noise Judgment Settings:
//
// CONFIG_ENABLE_NOISE_JUDGEMENT is not set

//
// 
//
#define CONFIG_LVP_STANDBY_ENABLE
// CONFIG_LVP_DISABLE_XIP_WHILE_CODE_RUN_AT_SRAM is not set
// CONFIG_LVP_ENABLE_ENERGY_VAD is not set
#define CONFIG_LVP_STATE_FVAD_COUNT_DOWN 18

//
// 
//
// CONFIG_LVP_ENABLE_KEYWORD_RECOGNITION is not set

//
// 
//
// CONFIG_LVP_ENABLE_VOICE_PRINT_RECOGNITION is not set

//
// 
//
#define CONFIG_LVP_ENABLE_SED
#define CONFIG_SED_SNPU_BUFFER_SIZE 776
#define CONFIG_SED_MODEL_FEATURES_DIM_PER_FRAME 256
#define CONFIG_SED_MODEL_FEATURES_PADDING_NUM 0
#define CONFIG_SED_MODEL_EFFECTIVE_FEATURES_PER_FRAME 256
#define CONFIG_SED_MODEL_INPUT_STRIDE_LENGTH 1
#define CONFIG_SED_MODEL_INPUT_WIN_LENGTH 1
#define CONFIG_SED_MODEL_OUTPUT_LENGTH 2
#define CONFIG_LVP_ENABLE_RNN_SED
#define CONFIG_LVP_RNN_SED_MODEL
#define CONFIG_LVP_ENABLE_RNN_SED_STATE_RESET
#define CONFIG_LVP_ENABLE_RNN_SED_STATE_RESET_INTERVAL 10
// CONFIG_LVP_RNN_SED_MODEL_V0_0_1_2023_0712 is not set
// CONFIG_LVP_RNN_SED_MODEL_V0_0_2_2023_0725 is not set
// CONFIG_LVP_RNN_SED_MODEL_V0_0_3_2023_0803 is not set
// CONFIG_LVP_RNN_SED_MODEL_V0_0_4_2023_0815 is not set
// CONFIG_LVP_RNN_SED_MODEL_V0_0_5_2023_0901 is not set
#define CONFIG_LVP_RNN_SED_MODEL_V0_1_1_2024_0116
// CONFIG_LVP_RNN_SED_MODEL_V1_0_1_2023_1023 is not set
// CONFIG_LVP_RNN_SED_MODEL_V1_0_2_2024_0105 is not set

//
// Model Param Setting:
//
#define CONFIG_ENABLE_POST_PROCESSING
#define CONFIG_POST_PROCESSING_DEVELOPMENT
#define CONFIG_VED_SNORING_THRESHOLD 999
#define CONFIG_VED_BABYCRYING_THRESHOLD 68
// CONFIG_POST_PROCESSING_DEVELOPMENT_V0_0_1_2023_0725 is not set
#define CONFIG_POST_PROCESSING_DEVELOPMENT_V0_0_2_2023_0901

//
// Post Process Setting:
//

//
// 
//

//
// LVP Application Settings
#endif // __VUI_CONF_H__
